apiVersion: v1
kind: Service
metadata:
  name: flask-monitor-svc
spec:
  selector:
    app: flask-monitor
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
